# **Regressão Logística**

In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pickle
import pandas as pd
import numpy as np

### Base de Risco de Crédito

In [10]:
with open('risco_credito.pkl',mode='rb') as f:
    [X_risco_credito, y_risco_credito] = pickle.load(f)

In [11]:
X_risco_credito = np.delete(X_risco_credito, [2,7,11], axis=0)
y_risco_credito = np.delete(y_risco_credito, [2,7,11], axis=0)

In [13]:
from sklearn.linear_model import LogisticRegression

logistic_risco_credito = LogisticRegression(random_state=1)
logistic_risco_credito.fit(X=X_risco_credito, y=y_risco_credito)

display(logistic_risco_credito.coef_)
display(logistic_risco_credito.intercept_)

array([[-0.76706797,  0.23921064, -0.47989768,  1.12196145]])

array([-0.80855152])

In [14]:
previsoes = logistic_risco_credito.predict([[0,0,1,2],[2,0,0,0]])
previsoes

array(['baixo', 'alto'], dtype=object)

### Base de Crédito

In [6]:
with open('/Users/gustavomeira/Documents/Python/Estudo_ML/projects/Classificação/credit.pkl',mode='rb') as f:
    [X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste] = pickle.load(f)
    
X_credit_treinamento = np.array(X_credit_treinamento)
y_credit_treinamento = np.array(y_credit_treinamento)
X_credit_teste = np.array(X_credit_teste)
y_credit_teste = np.array(y_credit_teste)

In [16]:
logistic_credit = LogisticRegression(random_state=1)
logistic_credit.fit(X=X_credit_treinamento, y=y_credit_treinamento)

previsoes = logistic_credit.predict(X=X_credit_teste)

In [17]:
print(accuracy_score(y_credit_teste,previsoes),'\n')
print(confusion_matrix(y_credit_teste,previsoes),'\n')
print(classification_report(y_credit_teste,previsoes))

0.946 

[[423  13]
 [ 14  50]] 

              precision    recall  f1-score   support

           0       0.97      0.97      0.97       436
           1       0.79      0.78      0.79        64

    accuracy                           0.95       500
   macro avg       0.88      0.88      0.88       500
weighted avg       0.95      0.95      0.95       500



### Base do Censo

In [18]:
with open('/Users/gustavomeira/Documents/Python/Estudo_ML/projects/Classificação/census.pkl',mode='rb') as f:
    [X_census_treinamento, y_census_treinamento, X_census_teste, y_census_teste] = pickle.load(f)

X_census_treinamento = np.array(X_census_treinamento)
y_census_treinamento = np.array(y_census_treinamento)
X_census_teste = np.array(X_census_teste)
y_census_teste = np.array(y_census_teste)

In [19]:
logistic_census = LogisticRegression(random_state=1)
logistic_census.fit(X=X_census_treinamento, y=y_census_treinamento)

previsoes = logistic_census.predict(X=X_census_teste)

In [20]:
print(accuracy_score(y_census_teste,previsoes),'\n')
print(confusion_matrix(y_census_teste,previsoes),'\n')
print(classification_report(y_census_teste,previsoes))

0.8497441146366428 

[[3424  269]
 [ 465  727]] 

              precision    recall  f1-score   support

       <=50K       0.88      0.93      0.90      3693
        >50K       0.73      0.61      0.66      1192

    accuracy                           0.85      4885
   macro avg       0.81      0.77      0.78      4885
weighted avg       0.84      0.85      0.84      4885

